[build-system]
# Defines the tools required to build the package
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "picamerautils"  # Required: the name of your package
version = "1.0.0"      # Required: project version
description = "Utilities and Apps for the Picamera2 Library"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "LueyTheLooper", email = "adamlsherwin@gmail.com"}
]
dependencies = [
    "opencv-python",
    "flask",
    "numpy",
    "picamera2",
]

[project.scripts]
simple-stream = "picamerautils.apps.flask_server:main"

[tool.setuptools.packages.find]
# "where" tells setuptools to look for packages inside the "src" directory
where = ["src"]
# "include" can be used to limit discovery to specific patterns
include = ["*"]
# Set to false if you do not want to use PEP 420 namespace packages
namespaces = false

